"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.__esModule = true;
exports.IERC20DecimalsWrapper__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [],
        name: "decimals",
        outputs: [
            {
                internalType: "uint8",
                name: "",
                type: "uint8"
            },
        ],
        stateMutability: "view",
        type: "function"
    },
];
var IERC20DecimalsWrapper__factory = /** @class */ (function () {
    function IERC20DecimalsWrapper__factory() {
    }
    IERC20DecimalsWrapper__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    IERC20DecimalsWrapper__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    IERC20DecimalsWrapper__factory.abi = _abi;
    return IERC20DecimalsWrapper__factory;
}());
exports.IERC20DecimalsWrapper__factory = IERC20DecimalsWrapper__factory;
