name: Actions

on: push

jobs:
  build:
    name: Run tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Run tsc
        run: yarn run tsc

  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Run eslint
        run: yarn run lint

  test:
    name: Run tests
    runs-on: ubuntu-latest

    # Docker Hub image that `container-job` executes in
    container: node:14.17.3-buster

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Install project dependencies
        run: yarn

      - name: Install psql
        run: |
          apt-get update
          apt-get install --yes postgresql-client

      - name: Setup test database
        # Run a script that creates the test database and test user
        run: yarn ts-node ci/createTestDatabase.ts
        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: 5432

      - name: Migrate database
        run: yarn run migrate:ci up

      - name: Run jest
        run: yarn run test:ci
